version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: usermgmt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_usermgmt:/var/lib/postgresql/data
      - ./userMgmtMicroservice/docker/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ms_user -d microservice_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata_usermgmt: